apiVersion: apps/v1
kind: Deployment
metadata:
  name: biokyc-dev
  labels:
    app: biokyc-dev
  annotations:
spec:
  selector:
    matchLabels:
      app: biokyc-dev
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: biokyc-dev
    spec:
      containers:
      - name: biokyc-dev
        image: kiyange26773/nginxphprediscomposer_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"
